standard:
  directories:
    - "**/.js"
    - "!test/integration/packages/**/*.js"
suites:
  unit: 
    - name: unit
      test:
        specs: test/unit
      coverage:
        config:
          dir: .coverage/unit
  integration:
    - name: api-docker-coverage
      before:
        local:
          command: test/integration/commands/prepare-package.sh
          env:
            package_to_launch: api
            narval_config: api-docker-coverage
      services:
        - name: package-test
          local:
            command: test/integration/commands/launch-test.sh
            env:
              package_to_launch: api
      test:
        specs:
          - test/integration/specs/exit/exit-ok.specs.js
          - test/integration/specs/coverage/json.specs.js
          - test/integration/specs/coverage/lcov.specs.js
          - test/integration/specs/coverage/summary.specs.js
          - test/integration/specs/logs/service.logs.specs.js
          - test/integration/specs/api-docker-coverage/common.specs.js
          - test/integration/specs/api-docker-coverage/test-ok.specs.js
        local:
          wait-on:
            resources: 
              - .narval/logs/integration/api-docker-coverage/package-test/exit-code.log
            timeout: 120000
          env:
            package_to_launch: api
            coverage_dir: .coverage/end-to-end/books-api
            logs_folder: end-to-end/books-api
      coverage:
        enabled: false
    - name: api-docker-coverage-test-ko
      before:
        local:
          command: test/integration/commands/prepare-package.sh
          env:
            package_to_launch: api
            narval_config: api-docker-coverage-test-ko
      services:
        - name: package-test
          local:
            command: test/integration/commands/launch-test.sh
            env:
              package_to_launch: api
      test:
        specs:
          - test/integration/specs/exit/exit-ko.specs.js
          - test/integration/specs/logs/service.logs.specs.js
          - test/integration/specs/coverage/not-json.specs.js
          - test/integration/specs/api-docker-coverage/common.specs.js
          - test/integration/specs/api-docker-coverage/test-ko.specs.js
        local:
          wait-on:
            resources: 
              - .narval/logs/integration/api-docker-coverage-test-ko/package-test/exit-code.log
            timeout: 120000
          env:
            package_to_launch: api
            coverage_dir: .coverage/end-to-end/books-api
            logs_folder: end-to-end/books-api
      coverage:
        enabled: false
