# From image
FROM {{from}}

ARG command_to_run
ENV command_to_run=$command_to_run

ARG test_specs
ENV test_specs=$test_specs

ARG coverage_dir
ENV coverage_dir=$coverage_dir

# Set the working directory
WORKDIR /app

# Copy resources
ADD ./install-resources .
ADD ./docker-resources .

# Copy resources
RUN ["chmod", "-R", "775", "."]
RUN ["ls", "-la"]

# Run install script
RUN ./.narval-install.sh

# Expose ports
{{#each expose}}
EXPOSE {{this}}
{{/each}}

# Start service
CMD ["sh", "-c", "./.narval-run-cmd.sh ${command_to_run} ${test_specs} ${coverage_dir}"]
